// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as HeadingComponent from "../../HeadingComponent.bs.js";
import * as PriceSectionPlusComponentModuleScss from "./PriceSectionPlusComponent.module.scss";

var css = PriceSectionPlusComponentModuleScss;

function PriceSectionPlusComponent(props) {
  return React.createElement("li", undefined, React.createElement(HeadingComponent.make, {
                  className: css.heading,
                  sub: true,
                  children: props.title
                }), React.createElement("p", undefined, props.description));
}

var make = PriceSectionPlusComponent;

export {
  make ,
}
/* css Not a pure module */
