// Generated by ReScript, PLEASE EDIT WITH CARE


function inlineOptionToString(inlineOption) {
  switch (inlineOption) {
    case "Start" :
        return "start";
    case "Center" :
        return "center";
    case "End" :
        return "end";
    case "Nearest" :
        return "nearest";
    
  }
}

function blockOptionToString(blockOption) {
  switch (blockOption) {
    case "Start" :
        return "start";
    case "Center" :
        return "center";
    case "End" :
        return "end";
    case "Nearest" :
        return "nearest";
    
  }
}

export {
  inlineOptionToString ,
  blockOptionToString ,
}
/* No side effect */
