// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as HeadingComponent from "../HeadingComponent.bs.js";
import * as AccordionComponent from "../AccordionComponent.bs.js";
import * as ContainerComponent from "../ContainerComponent.bs.js";
import * as IndexPageFaqModuleScss from "./IndexPageFaq.module.scss";

var css = IndexPageFaqModuleScss;

var accordionItems = [
  {
    title: "Что лучше надеть?",
    content: "Удобную обувь и одежду, игра активная."
  },
  {
    title: "Можно ли приносить свою еду?",
    content: "Да. Вы можете принести свою еду, а также заранее заказать доставку."
  },
  {
    title: "Это безопасно?",
    content: "Конечно! Игра бесконтактная, а инфракрасное излучение, на котором основан лазертаг, абсолютно безопасно, что позволяет играть даже самым маленьким."
  },
  {
    title: "Возможно ли присматривать за ребенком во время игры?",
    content: "Да, в комнате отдыха есть экран, по которому через камеры видеонаблюдения можно следить за игрой."
  },
  {
    title: "Расскажите про сценарии",
    content: "У нас большое разнообразие сценариев:\n\n- Командная перестрелка\n- Захват точки\n- Освобождение заложника\n- Обезвреживание бомбы\n- Ночной режим\n- Зомби\n- и другие\n\nИнструктор планирует игровой сценарий индивидуально."
  },
  {
    title: "Сколько может быть игроков?",
    content: "Мы проводим игры от 6-ти до 30-ти игроков, но гостей может быть и больше."
  }
];

function IndexPageFaq(props) {
  return React.createElement("section", {
              className: css.faqSection,
              id: props.id
            }, React.createElement(ContainerComponent.make, {
                  inner: true,
                  children: null
                }, React.createElement(HeadingComponent.make, {
                      children: "Часто задаваемые вопросы"
                    }), React.createElement(AccordionComponent.make, {
                      items: accordionItems
                    })));
}

var make = IndexPageFaq;

export {
  css ,
  accordionItems ,
  make ,
}
/* css Not a pure module */
