// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as React from "react";
import * as TextComponent from "../TextComponent.bs.js";
import * as HeadingComponent from "../HeadingComponent.bs.js";
import * as ContainerComponent from "../ContainerComponent.bs.js";
import * as JsxPPXReactSupportU from "rescript/lib/es6/jsxPPXReactSupportU.js";
import * as IndexPagePricesInfoModuleScss from "./IndexPagePricesInfo.module.scss";

var css = IndexPagePricesInfoModuleScss;

var items = [
  {
    title: "Важная информация!",
    content: "\nОсмотр арены только по записи\n      \nИгра проводится по предварительной брони с предоплатой\n      \nРекомендуем бронировать за 2-3 недели\n    "
  },
  {
    title: "Скидка",
    content: "\nОт **10** игроков - *2000р*  \nОт **14** игроков - *4000р*  \nОт **18** игроков - *8000р*  \nОт **22** игроков - *12000р*  \nОт **26** игроков - *16000р*  \nОт **30** игроков - *20000р*\n    "
  }
];

function IndexPagePricesInfo$SpecialInfo(props) {
  return React.createElement("div", {
              className: Cx.cx([
                    props.className,
                    css.specialInfoWrapper
                  ])
            }, items.map(function (param, idx) {
                  var title = param.title;
                  var isFirst = idx === 0;
                  return JsxPPXReactSupportU.createElementVariadicWithKey(title, React.Fragment, {
                              children: null
                            }, [
                              React.createElement(HeadingComponent.make, {
                                    className: Cx.cx(isFirst ? [css.specialInfoFirstHeading] : []),
                                    sub: true,
                                    children: title
                                  }),
                              React.createElement(TextComponent.make, {
                                    className: css.specialInfoOfferContent,
                                    content: param.content
                                  })
                            ]);
                }));
}

var SpecialInfo = {
  items: items,
  make: IndexPagePricesInfo$SpecialInfo
};

function IndexPagePricesInfo(props) {
  return React.createElement("section", {
              className: css.priceInfoSection,
              id: props.id
            }, React.createElement(ContainerComponent.make, {
                  className: css.content,
                  children: null
                }, React.createElement("div", {
                      className: css.attentionArrow
                    }, "Цены"), React.createElement(IndexPagePricesInfo$SpecialInfo, {
                      className: css.specialOffers
                    })));
}

var make = IndexPagePricesInfo;

export {
  css ,
  SpecialInfo ,
  make ,
}
/* css Not a pure module */
