// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TextComponent from "../TextComponent.bs.js";
import * as HeadingComponent from "../HeadingComponent.bs.js";
import * as ContainerComponent from "../ContainerComponent.bs.js";
import * as IndexPageAboutUsModuleScss from "./IndexPageAboutUs.module.scss";

var css = IndexPageAboutUsModuleScss;

function IndexPageAboutUs$GameCard(props) {
  return React.createElement("li", {
              className: css.gameCard
            }, React.createElement(HeadingComponent.make, {
                  className: css.gameCardHeading,
                  sub: true,
                  children: props.title
                }), React.createElement(TextComponent.make, {
                  content: props.description
                }));
}

var GameCard = {
  make: IndexPageAboutUs$GameCard
};

function IndexPageAboutUs(props) {
  return React.createElement("section", {
              className: css.section,
              id: props.id
            }, React.createElement(ContainerComponent.make, {
                  inner: true,
                  children: null
                }, React.createElement(HeadingComponent.make, {
                      children: "О нас"
                    }), React.createElement(TextComponent.make, {
                      content: "PANTHEON — это крытая арена спортивно-тактических игр в Мытищах и отличное место активного отдыха как для детей, так и для взрослых.\n\nПлощадка 400кв.м, в 10 минутах ходьбы от станции Мытищи и ТЦ Красный Кит."
                    }), React.createElement("ul", {
                      className: css.gamesList
                    }, React.createElement(IndexPageAboutUs$GameCard, {
                          title: "Стандартные лазертаг режимы",
                          description: "- Командный бой\n- Захват контрольных точек\n- Оборона\n- Заражение\n\nи другие..."
                        }), React.createElement(IndexPageAboutUs$GameCard, {
                          title: "Специальные лазертаг режимы",
                          description: "- Командные прятки в темноте\n- Обезвреживание бомбы\n- Снайперы\n- Последний герой\n\nи другие..."
                        }), React.createElement(IndexPageAboutUs$GameCard, {
                          title: "Интерактивная комната отдыха",
                          description: "- Аэрохоккей\n- Игровые приставки\n- Just Dance\n- Аркадная ретро консоль"
                        }), React.createElement(IndexPageAboutUs$GameCard, {
                          title: "Финальный Boss раунд",
                          description: "(с элементами Экшн-Квеста)\n\nЗаключительное испытание для всей команды с необычным светозвуковым сопровождением и участием аниматора в роли противника."
                        }))));
}

var make = IndexPageAboutUs;

export {
  css ,
  GameCard ,
  make ,
}
/* css Not a pure module */
