// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as HeadingComponent from "../HeadingComponent.bs.js";
import * as ContainerComponent from "../ContainerComponent.bs.js";
import * as IndexPagePriceCards from "./IndexPagePriceCards.bs.js";
import * as IndexPagePackPricesSectionModuleScss from "./IndexPagePackPricesSection.module.scss";

var css = IndexPagePackPricesSectionModuleScss;

var priceCards = [
  {
    title: "GAME",
    description: "Цена за 1 игрока\nИменинник бесплатно\nМинимальная группа 6 человек",
    points: [
      "**2 часа** игры лазертаг",
      "Финальный Boss раунд с элементами экшн-квеста"
    ],
    weekDayPrice: 1900,
    price: 2200,
    gradeColor: "#00c2ff"
  },
  {
    title: "SUPER",
    description: "Цена за 1 игрока\nИменинник бесплатно\nМинимальная группа 6 человек",
    points: [
      "**1.5 часа** игры лазертаг",
      "**1 час** интерактивной комнаты отдыха для проведения торжества",
      "Финальный Boss раунд с элементами экшн-квеста"
    ],
    weekDayPrice: 1900,
    price: 2200,
    isAccented: true,
    gradeColor: "#b000f1"
  },
  {
    title: "ULTRA",
    description: "Цена за 1 игрока\nИменинник бесплатно\nМинимальная группа 10 человек",
    points: [
      "**2.5 часа** игры лазертаг",
      "**1 час** интерактивной комнаты отдыха для проведения торжества",
      "Финальный Boss раунд с элементами экшн-квеста"
    ],
    weekDayPrice: 2600,
    price: 2900,
    gradeColor: "#ffbf20"
  }
];

function make() {
  return React.createElement("section", {
              className: css.section,
              id: "pack-prices-section"
            }, React.createElement(ContainerComponent.make, {
                  children: null
                }, React.createElement(HeadingComponent.make, {
                      className: css.heading,
                      children: "Наши тарифы"
                    }), React.createElement(IndexPagePriceCards.make, {
                      priceCards: priceCards,
                      className: css.priceCards
                    })));
}

export {
  css ,
  priceCards ,
  make ,
}
/* css Not a pure module */
