// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as React from "react";
import * as Core__Option from "@dzakh/rescript-core/src/Core__Option.bs.js";
import * as BoxModuleScss from "./Box.module.scss";

var css = BoxModuleScss;

function Box(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return React.createElement("div", {
              className: Cx.cx([
                    css.default,
                    props.alignItems !== undefined ? css.alignItems_baseline : "",
                    className
                  ]),
              style: {
                gap: Core__Option.map(props.space, (function (size) {
                        return (size << 2).toString() + "rem";
                      }))
              }
            }, props.children);
}

var make = Box;

export {
  css ,
  make ,
}
/* css Not a pure module */
