// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as React from "react";
import * as HeadingComponentModuleScss from "./HeadingComponent.module.scss";

var css = HeadingComponentModuleScss;

function HeadingComponent(props) {
  var children = props.children;
  var __pure = props.pure;
  var __sub = props.sub;
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  var sub = __sub !== undefined ? __sub : false;
  var pure = __pure !== undefined ? __pure : false;
  if (sub) {
    return React.createElement("h3", {
                className: Cx.cx([
                      className,
                      pure ? css.pure : css.subHeading
                    ])
              }, children);
  } else {
    return React.createElement("h2", {
                className: Cx.cx([
                      className,
                      pure ? css.pure : css.heading
                    ])
              }, children);
  }
}

var make = HeadingComponent;

export {
  make ,
}
/* css Not a pure module */
