// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function LocalImageComponent(props) {
  return React.createElement("img", {
              className: props.className,
              alt: props.alt,
              height: props.height,
              src: props.src,
              width: props.width
            });
}

var make = LocalImageComponent;

export {
  make ,
}
/* react Not a pure module */
