// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SpreadComponent from "./SpreadComponent.bs.js";
import * as SmoothSmoothScroll from "../bindings/SmoothSmoothScroll.bs.js";

function PageInnerLinkComponent(props) {
  var __block = props.block;
  var __inline = props.inline;
  var inline = __inline !== undefined ? __inline : "Nearest";
  var block = __block !== undefined ? __block : "Start";
  return React.createElement(SpreadComponent.make, {
              props: {
                "data-smooth-scroll-to": props.to,
                "data-smooth-scroll-inline": SmoothSmoothScroll.inlineOptionToString(inline),
                "data-smooth-scroll-block": SmoothSmoothScroll.blockOptionToString(block)
              },
              children: React.createElement("button", {
                    className: props.className,
                    type: "button"
                  }, props.children)
            });
}

var make = PageInnerLinkComponent;

export {
  make ,
}
/* react Not a pure module */
