// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Head from "next/head";
import * as FaviconMetaComponentJsx from "./FaviconMetaComponent.jsx";

var make = FaviconMetaComponentJsx.FaviconMetaComponent;

function SeoComponent(props) {
  var siteName = props.siteName;
  var description = props.description;
  var title = props.title;
  return React.createElement(React.Fragment, {
              children: null
            }, React.createElement(Head, {
                  children: null
                }, React.createElement("title", undefined, title), description !== undefined ? React.createElement("meta", {
                        content: description,
                        name: "description"
                      }) : null, React.createElement("meta", {
                      content: "website",
                      property: "og:type"
                    }), React.createElement("meta", {
                      content: title,
                      property: "og:title"
                    }), description !== undefined ? React.createElement("meta", {
                        content: description,
                        property: "og:description"
                      }) : null, siteName !== undefined ? React.createElement("meta", {
                        content: siteName,
                        property: "og:site_name"
                      }) : null, React.createElement("meta", {
                      content: "summary",
                      property: "twitter:card"
                    }), React.createElement("meta", {
                      content: title,
                      property: "twitter:title"
                    }), description !== undefined ? React.createElement("meta", {
                        content: description,
                        property: "twitter:description"
                      }) : null), React.createElement(make, {}));
}

var make$1 = SeoComponent;

export {
  make$1 as make,
}
/* make Not a pure module */
