// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as React from "react";
import * as PageInnerLinkComponent from "./PageInnerLinkComponent.bs.js";
import * as SimpleReservationButtonComponentModuleScss from "./SimpleReservationButtonComponent.module.scss";

var css = SimpleReservationButtonComponentModuleScss;

function SimpleReservationButtonComponent(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return React.createElement(PageInnerLinkComponent.make, {
              className: Cx.cx([
                    css.container,
                    className
                  ]),
              block: "Center",
              to: "reservation-section",
              children: "Забронировать"
            });
}

var make = SimpleReservationButtonComponent;

export {
  make ,
}
/* css Not a pure module */
