// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Spacer(props) {
  var value = (props.size << 2).toString() + "rem";
  return React.createElement("div", {
              style: {
                height: value,
                width: value
              }
            });
}

var make = Spacer;

export {
  make ,
}
/* react Not a pure module */
