// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function SpreadComponent(props) {
  return React.cloneElement(props.children, props.props);
}

var make = SpreadComponent;

export {
  make ,
}
/* react Not a pure module */
