// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as React from "react";
import ReactMarkdown from "react-markdown";
import * as TextComponentModuleScss from "./TextComponent.module.scss";

var css = TextComponentModuleScss;

function TextComponent(props) {
  var __className = props.className;
  var className = __className !== undefined ? __className : "";
  return React.createElement(ReactMarkdown, {
              className: Cx.cx([
                    css.text,
                    className
                  ]),
              children: props.content
            });
}

var make = TextComponent;

export {
  make ,
}
/* css Not a pure module */
