// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var context = React.createContext(null);

function IndexPageContent$Provider(props) {
  return React.createElement(context.Provider, {
              value: props.pageContent,
              children: props.children
            });
}

var Provider = {
  make: IndexPageContent$Provider
};

function use() {
  return React.useContext(context);
}

export {
  Provider ,
  use ,
}
/* context Not a pure module */
