// Generated by ReScript, PLEASE EDIT WITH CARE


var config_siteMetadata = {
  name: "Лазертаг Pantheon",
  title: "Праздник с Лазертаг в Мытищах «Pantheon»",
  description: "Отметьте праздник на крытой лазертаг-арене в 10-ти минутах от станции Мытищи. Вы выбираете во что играть, а с нас остальное."
};

var config_sanity = {
  projectId: "nk6o1twh",
  dataset: "promo",
  useCdn: false
};

var config_ym = {
  trackingId: 55340875
};

var config_googleFonts = {
  families: ["Open+Sans:wght@300;400;700"],
  display: "swap"
};

var config = {
  siteMetadata: config_siteMetadata,
  sanity: config_sanity,
  ym: config_ym,
  googleFonts: config_googleFonts
};

export {
  config ,
}
/* No side effect */
