// Generated by ReScript, PLEASE EDIT WITH CARE


var telNumber = "+7 977 722 09 60";

var vkLink = "https://vk.com/club.pantheon";

var instLink = "https://www.instagram.com/pantheon_arena/";

var whatsappLink = "https://api.whatsapp.com/send?phone=79777220960";

export {
  telNumber ,
  vkLink ,
  instLink ,
  whatsappLink ,
}
/* No side effect */
